CREATE TABLE IF NOT EXISTS `APPROVAL_ETC`
(
    `AE_CODE`    VARCHAR(255) NOT NULL COMMENT '기타결재코드',
    `AE_CON`    VARCHAR(255) NOT NULL COMMENT '결재내용',
    PRIMARY KEY ( `AE_CODE` )
    )ENGINE=INNODB COMMENT = '기타결재';

CREATE TABLE IF NOT EXISTS `APPROVAL_APPOINT`
(
    `AAPP_CODE`    VARCHAR(255) NOT NULL COMMtrue_app_lineENT '발령결재코드',
    `AAPP_NO`    VARCHAR(255) NOT NULL COMMENT '발령번호',
    `AAPP_DATE`    DATE NOT NULL COMMENT '발령일',
    `AAPP_TITLE`    VARCHAR(255) NOT NULL COMMENT '발령제목',
    PRIMARY KEY ( `AAPP_CODE` )
    )ENGINE=INNODB COMMENT = '발령결재';

CREATE TABLE IF NOT EXISTS `APPOINT_DETAIL`
(
    `ADET_CODE`		INTEGER NOT NULL AUTO_INCREMENT COMMENT '발령결재상세코드',
    `AAPP_CODE`    VARCHAR(255) NOT NULL COMMENT '발령결재코드',
    `AAPP_BEFORE`    VARCHAR(255) NOT NULL COMMENT '발령전',
    `AAPP_AFTER`    VARCHAR(255) NOT NULL COMMENT '발령후',
    `AAPP_TYPE`    VARCHAR(255) NOT NULL COMMENT '발령종류',
    `EMP_CODE`    INTEGER NOT NULL COMMENT '사원 코드',
    PRIMARY KEY ( `ADET_CODE` )
    )ENGINE=INNODB COMMENT = '발령결재상세';


CREATE TABLE IF NOT EXISTS `APPROVAL_PERSONAL`
(
    `AP_CODE`    VARCHAR(255) NOT NULL COMMENT '인사결재코드',
    `AP_START`    DATE NOT NULL COMMENT '시작일',
    `AP_END`    DATE COMMENT '종료일',
    `AP_CONTACT`    VARCHAR(255) NOT NULL COMMENT '비상연락처',
    `AP_REASON`    VARCHAR(255) NOT NULL COMMENT '사유',
    PRIMARY KEY ( `AP_CODE` )
    )ENGINE=INNODB COMMENT = '인사결재';

CREATE TABLE IF NOT EXISTS `APPROVAL_ATTENDANCE`
(
    `AATT_CODE`    VARCHAR(255) NOT NULL COMMENT '근태결재코드',
    `AATT_SORT`    VARCHAR(255) COMMENT '분류',
    `AATT_START`    DATETIME COMMENT '시작일',
    `AATT_END`    DATETIME COMMENT '종료일',
    `AATT_OCCUR`    DATE COMMENT '발생일',
    `AATT_PLACE`    VARCHAR(255) COMMENT '근무지',
    `AATT_CON`    VARCHAR(255) COMMENT '내용',
    `AATT_REASON`    VARCHAR(255) COMMENT '사유',
    PRIMARY KEY ( `AATT_CODE` )
    )ENGINE=INNODB COMMENT = '근태결재';

CREATE TABLE IF NOT EXISTS `APPROVAL_FORM`
(
    `AF_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재양식코드',
    `AF_NAME`    VARCHAR(255) NOT NULL COMMENT '결제양식명',
    `AF_EXPLAIN`    VARCHAR(255) COMMENT '결제양식설명',
    `LS_CODE`    INTEGER NOT NULL COMMENT '결재라인분류코드',
    PRIMARY KEY ( `AF_CODE` )
    )ENGINE=INNODB COMMENT = '결재양식';


CREATE TABLE IF NOT EXISTS `APPROVAL_BOX`
(
    `AB_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재보관함코드',
    `AB_NAME`    VARCHAR(255) NOT NULL COMMENT '결재보관함명',
    `EMP_CODE`    INTEGER NOT NULL COMMENT '사원 코드',
    PRIMARY KEY ( `AB_CODE` )
    )ENGINE=INNODB COMMENT = '결재보관함';

CREATE TABLE IF NOT EXISTS `APPROVAL_STORAGE`
(
    `AS_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재보관코드',
    `AD_CODE`    VARCHAR(255) NOT NULL COMMENT '결재문서코드',
    `AB_CODE`    INTEGER NOT NULL COMMENT '결재보관함코드',
    PRIMARY KEY ( `AS_CODE` )
    )ENGINE=INNODB COMMENT = '결재보관내역';

CREATE TABLE IF NOT EXISTS `APPROVAL_DOC`
(
    `AD_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재문서코드',
    `AD_TITLE`    VARCHAR(255) NOT NULL COMMENT '결재문서제목',
    `EMP_CODE`    INTEGER NOT NULL COMMENT '작성자',
    `AD_REPORT_DATE`    DATE NOT NULL COMMENT '상신일',
    `AD_STATUS`    VARCHAR(255) NOT NULL COMMENT '문서상태',
    `AF_CODE`    INTEGER NOT NULL COMMENT '결재양식코드',
    `AD_DETAIL`	VARCHAR(255) NOT NULL COMMENT '결재문서상세',
    PRIMARY KEY ( `AD_CODE` )
    )ENGINE=INNODB COMMENT = '결재문서';

CREATE TABLE IF NOT EXISTS `TRUE_APP_LINE`
(
    `TAL_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '실결재라인코드',
    `TAL_ORDER`    INTEGER NOT NULL COMMENT '실결재자순서',
    `TAL_ROLE`    VARCHAR(255) NOT NULL COMMENT '실결재자역할',
    `AD_CODE`    VARCHAR(255) NOT NULL COMMENT '결재문서코드',
    `TAL_STATUS`    VARCHAR(255) COMMENT '실결재상태',
    `EMP_CODE`    INTEGER NOT NULL COMMENT '사원 코드(실결재자)',
    `TAL_REASON`    VARCHAR(255) COMMENT '반려 사유',
    `TAL_DATE`    DATE COMMENT '결재일',
    PRIMARY KEY ( `TAL_CODE` )
    )ENGINE=INNODB COMMENT = '실결재라인';

CREATE TABLE IF NOT EXISTS `APPROVAL_LINE`
(
    `AL_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재라인코드',
    `AL_SORT`	 VARCHAR(255) NOT NULL COMMENT '결재자',
    `AL_ORDER`   INTEGER NOT NULL COMMENT '결재순서',
    `AL_ROLE`    VARCHAR(255) NOT NULL COMMENT '결재역할' DEFAULT '결재',
    `LS_CODE`    INTEGER NOT NULL COMMENT '결재라인분류코드',
    PRIMARY KEY ( `AL_CODE` )
    )ENGINE=INNODB COMMENT = '결재라인';

CREATE TABLE IF NOT EXISTS `LINE_SORT`
(
    `LS_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '결재라인분류코드',
    `LS_NAME`    VARCHAR(255) NOT NULL COMMENT '결재라인분류명',
    PRIMARY KEY ( `LS_CODE` )
    )ENGINE=INNODB COMMENT = '결재라인분류';


CREATE TABLE IF NOT EXISTS `ATTACHMENT`
(
    `ATTACH_CODE`    INTEGER NOT NULL AUTO_INCREMENT COMMENT '첨부파일코드',
    `ATTACH_ORIGINAL`    VARCHAR(255) NOT NULL COMMENT '원본명',
    `ATTACH_SAVE`    VARCHAR(255) NOT NULL COMMENT '저장명',
    `ATTACH_URL`    VARCHAR(255) NOT NULL COMMENT '경로',
    `ATTACH_SORT` VARCHAR(255) NOT NULL COMMENT '첨부파일 분류',
    PRIMARY KEY ( `ATTACH_CODE` )
    )ENGINE=INNODB COMMENT = '첨부파일';