spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/groupware?allowPublicKeyRetrieval=true&useSSL=true
    url: jdbc:mysql://localhost:3306/groupware
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      location: C:/SynergyHub
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

# image upload dir
image:
  profile-image-dir: C:/SynergyHub/profileimgs
  approval-attach-dir: C:/SynergyHub/approval
  post-image-dir: C:/SynergyHub/postimgs
  message-image-dir: C:/SynergyHub/messageimgs
  profile-image-url: http://localhost:8080/profileimgs
  approval-image-url: http://localhost:8080/approvalimgs
  post-image-url: http://localhost:8080/postimgs
  message-image-url: http://localhost:8080/messageimgs

server:
  port: 8080

jwt:
  secret: asdfjk12938fu08bh3rhq2387qfe8hjvweh2w93ur9djvhw983o3uew23rfgeiv8hewsor2hjdhxmzqw83o832 #??? ???
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000