### 결재양식리스트 조회
GET http://localhost:8080/approval/formList

### 결재라인 전체 조회
GET http://localhost:8080/approval/formLine

### 결재라인 특정 조회
GET http://localhost:8080/approval/formLine?lsCode=3

### 결재라인 회원 조회(본인 기준)
GET http://localhost:8080/approval/formLineEmp?deptCode=D15&titleCode=T6&lsCode=3

### 결재서명 조회(본인 기준)
GET http://localhost:8080/approval/sign?empCode=2021048





### 보낸 결재함 전체 조회 (작성자 기준)
GET http://localhost:8080/approval/document?empCode=2021048

### 받은 결재함 전체 조회 ()