### 사원등록
POST http://localhost:8080/employee/empRegist
Content-Type:application/json

{

  "emp_code": "",
  "emp_name": "이복구",
  "emp_pass": "",
  "social_security_no": "111111-2222222",
  "dept_code": "D5",
  "position_code": "P5",
  "title_code": "T6",
  "hire_date": "2024-06-12",
  "emp_status": "Y"
}

### 로그인 테스트
POST http://localhost:8080/emp/auth/login
Content-Type: application/json

{
  "emp_code" : "2024062",
  "emp_pass" : "2024062"
}

//@emp_code = 2024062
### 내정보 조회
GET http://localhost:8080/employee/myInfo
Authorization: Bearer eyJkYXRlIjoxNzE5NTU2OTQ2NTI1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYyLCJleHAiOjE3MTk1NjA1NDZ9.1eQO0AoTbyLbbHjD8A4E7xyIccZJuaXXrzH8hfH29_rtQck61umuy9WgBStwtHRfjdJb4EatOvjhhFEQafHn6A


### 인사기록카드 조회
GET http://localhost:8080/employee/recordCard
Authorization: Bearer eyJkYXRlIjoxNzE4OTM0ODU2NjY1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIwMDIxLCJleHAiOjE3MTg5Mzg0NTZ9.o9fp7DwEpTr5FUsB0T1tnsB275qRcPRlh6l1hn4D_MlTYn3yySYe7kDdWNszBA4hViIKCxyz5YXDVHpF4hL8Cg

### 팀원 정보 조회
GET http://localhost:8080/employee/employeeList
Authorization: Bearer eyJkYXRlIjoxNzE4ODEyNjc0NjU3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYyLCJleHAiOjE3MTg4MTYyNzR9.VtwyIYOipD3NrgxYCC3ZiBaFRxdOv8RvZ3Y64ujW8VPpfNySWKJaUAdaXY22fFHwn3NZO-paK3JbN6E6NoyxlA

### 부서 전체 조회
GET http://localhost:8080/employee/departments

### 부서 상세 조회
GET http://localhost:8080/employee/departmentList/D1

### 조직도 전체 조회
GET http://localhost:8080/employee/org

### 조직도 상세 조회
GET http://localhost:8080/employee/orgDetail/{{emp_code}}

### 비밀번호 사원코드로 초기화
PATCH http://localhost:8080/employee/resetEmpPass/2021011
Authorization: Bearer eyJkYXRlIjoxNzE4OTM1ODkzNzk2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYyLCJleHAiOjE3MTg5Mzk0OTN9.yXlDrBV_peVP9znDckR8BAJe9hDusW0y-NTaukLW9llGXlBCtb5lvXkZEFXq98vXCHpu5iH5uoiqeM-Tp15OYQ





