### 사원등록
POST http://localhost:8080/employee/empsRegist
Content-Type:application/json

[
  {
    "emp_code": "",
    "emp_name": "테스터1",
    "emp_pass": "",
    "social_security_no": "111111-2222222",
    "dept_code": "D5",
    "position_code": "P5",
    "title_code": "T6",
    "hire_date": "2024-06-27",
    "emp_status": "Y",
    "detailErdCode": "",
    "detailErdNum": "",
    "detailErdTitle": "테스트 인사등록1",
    "detailEmpCode": ""
  },
  {
    "emp_code": "",
    "emp_name": "테스터12",
    "emp_pass": "",
    "social_security_no": "333333-4444444",
    "dept_code": "D7",
    "position_code": "P8",
    "title_code": "T9",
    "hire_date": "2024-06-27",
    "emp_status": "Y",
    "detailErdCode": "",
    "detailErdNum": "",
    "detailErdTitle": "테스트 인사등록1",
    "detailEmpCode": ""
  },
  {
    "emp_code": "",
    "emp_name": "테스터13",
    "emp_pass": "",
    "social_security_no": "555555-6666666",
    "dept_code": "D7",
    "position_code": "P8",
    "title_code": "T9",
    "hire_date": "2024-06-27",
    "emp_status": "Y",
    "detailErdCode": "",
    "detailErdNum": "",
    "detailErdTitle": "테스트 인사등록1",
    "detailEmpCode": ""
  }
]



### 사원등록 상세정보 등록
POST http://localhost:8080/employee/empRegistDetail

### 로그인 테스트
POST http://localhost:8080/emp/auth/login
Content-Type: application/json

{
  "emp_code" : "2024062",
  "emp_pass" : "2024062"
}

//@emp_code = 2024062
### 내정보 조회
GET http://localhost:8080/employee/myInfo
Authorization: Bearer eyJkYXRlIjoxNzE5ODI4ODk2NjI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYyLCJleHAiOjE3MjA0MzM2OTZ9.9TXFK9SHkydFEx2bYD7x11HFxb_3-stXkxMEPb5NccZQnZl-yBmjE81M-vz3bi-Gl2rdDX_9T1u74MXv6knq1g

### 인사기록카드 조회
GET http://localhost:8080/employee/recordCard
Authorization: Bearer eyJkYXRlIjoxNzE5MzA0MTY2Mzc0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIwMDExLCJleHAiOjE3MTkzMDc3NjZ9.0ExrgU9p43ELJGjEEZdxS67qCJTQUAvlIzTOfZW0TaCslEcrmlFu1Tx8W3Icv9pXRzIzPjip5A9YBLfqQEjqSA

### 팀원 인사기록카드 조회
GET http://localhost:8080/employee/teamRecordCard/2021011
Authorization: Bearer eyJkYXRlIjoxNzE5MzEwMzAyNDAzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIwMDExLCJleHAiOjE3MTkzMTM5MDJ9.nsez9CagYHmVpU-5r6irl5kzvb5xtFAmsSpt8lJe-wvQ-fgMg4e-rLsnPd35aHGX2ttsoQIrXfBqrP-QFTQ-Vg

### 팀원 정보 조회
GET http://localhost:8080/employee/employeeList
Authorization: Bearer eyJkYXRlIjoxNzE5MzEwMzAyNDAzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIwMDExLCJleHAiOjE3MTkzMTM5MDJ9.nsez9CagYHmVpU-5r6irl5kzvb5xtFAmsSpt8lJe-wvQ-fgMg4e-rLsnPd35aHGX2ttsoQIrXfBqrP-QFTQ-Vg

### 부서 등록
POST http://localhost:8080/employee/registDept
Content-Type:application/json

{
  "dept_title": "부서생성테스트"
}

### 부서 상위 하위관계 등록
POST http://localhost:8080/employee/registDeptRelations
Content-Type:application/json

{
  "parentDepartment": {
    "dept_code": "D22"
  },
  "subDepartment": {
    "dept_code": "D23"
  }
}

### 부서 상위 하위관계 수정
PUT http://localhost:8080/employee/modifyDeptRelations/33
Content-Type:application/json

{
  "dept_relations_code": 33,
  "parentDepartment": {
    "dept_code": "D22"
  },
  "subDepartment": {
    "dept_code": "D24"
  }
}

### 부서 상위 하위관계 삭제
DELETE http://localhost:8080/employee/deleteDeptRelations
Content-Type:application/json

{
  "parentDepartment": {
    "dept_code": "D22"
  },
  "subDepartment": {
    "dept_code": "D23"
  }
}

### 부서 전체 조회
GET http://localhost:8080/employee/departments

### 부서 상세 조회
GET http://localhost:8080/employee/deptDetailList/D2

### 직급 전체 조회
GET http://localhost:8080/employee/empPositions

### 조직도 전체 조회
GET http://localhost:8080/employee/org

### 조직도 상세 조회
GET http://localhost:8080/employee/orgDetail/{{emp_code}}

### 비밀번호 사원코드로 초기화
PUT http://localhost:8080/employee/resetEmpPass/2024035
Authorization: Bearer eyJkYXRlIjoxNzE5Mjk0NTAzODcwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYyLCJleHAiOjE3MTkyOTgxMDN9.qX90Vu9uJJJ41hLDOGDlKbdcpHpAmWy2xmrRwR5xjycfZLdXFf7fdbHevf9YNXTlEjLH9ALt9xxy4Ix3TBeHiw






