### 로그인 테스트
POST http://localhost:8080/emp/auth/login
Content-Type: application/json

{
  "emp_code" : "2021067",
  "emp_pass" : "2021067"

}

### 회원 주소록 전체 조회
GET http://localhost:8080/address/select

### 받은 쪽지 전체 조회
GET http://localhost:8080/emp/message/receive
Authorization: Bearer eyJkYXRlIjoxNzE5Mzg3NTg3MTc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MTkzOTExODd9.2W0dlF1_3cY0_68-kF3DzN1cqGDiHxcrPC191pGUpuCkbK88z1xeZgsMQ-Q402zZ0qD1hx6q4RyIP4qR7Hzntg
### 보낸 쪽지 전체 조회
GET http://localhost:8080/emp/message/send
Authorization: Bearer eyJkYXRlIjoxNzE5NTU4ODg2MjU3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MTk1NjI0ODZ9.knrL_ZEhzsi8deI8URChDcPNkH7hSx1PS15d8Yx_SaQ1qVkrS8c6kueWMUPamF8SjR5-QHLBKcHH1lRVBDshuw

### 받은 쪽지 휴지통 PUT
PUT http://localhost:8080/emp/message/receive/MS40/bin
Content-Type: application/json

{
  "storCode": 2
}

### 휴지통 전체 조회
GET http://localhost:8080/emp/message/bin
Authorization: Bearer eyJkYXRlIjoxNzE5MzcwMTg2NjUyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MTkzNzM3ODZ9.P0E-tVtS64rPidQUanwPbFQtUTYRUvtynPIx-iwMqPHrsGzsWiwagEC8LR4fUFJSQ5062bbLrtJEueEkoicR2w

### 중요 보관함 전체 조회
GET http://localhost:8080/emp/message/important
Authorization: Bearer eyJkYXRlIjoxNzE5Mzg0MDAwNzgxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MTkzODc2MDB9.KcdwXsSFy-9poSbRc_aviihkBZ6Z3NSHZwdlbO_UUrW8pmhWGHp5kxVk7NtJMNeM8fk8PSOxOCy-Wos1nGqrFg

### 업무 보관함 전체 조회
GET http://localhost:8080/emp/message/work
Authorization: Bearer eyJkYXRlIjoxNzE5MzcwMTg2NjUyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MTkzNzM3ODZ9.P0E-tVtS64rPidQUanwPbFQtUTYRUvtynPIx-iwMqPHrsGzsWiwagEC8LR4fUFJSQ5062bbLrtJEueEkoicR2w

### Rev Msg Detail Get
GET http://localhost:8080/emp/message/receive/MS72

### Send Msg Detail Get
GET http://localhost:8080/emp/message/send/MS6

### Send Msg
POST http://localhost:8080/emp/message/send
Content-Type: application/json

{
  "msgTitle": "프로젝트 언제 끝납니까?",
  "msgCon": "7월 16일이요",
  "msgStatus": "N",
  "emerStatus": "N",
  "empRev": {"emp_code": "2022089"},
  "empSend": {"emp_code": "2021067"},
  "storCode": {"storCode": "1"}
}

### Temp Msg
GET http://localhost:8080/emp/message/temp
Authorization: Bearer eyJkYXRlIjoxNzE5Nzk0NTE3MDc2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDIxMDY3LCJleHAiOjE3MjAzOTkzMTd9.jRiWUljXpBYNdhiXaV3bGuqZ8ZOkDJiV_KgGJkKkJgV5RzUw-lWjMvUSa0nGgUPF65ySR_pL2YDygmbB3eHkbw
