### 로그인 테스트
POST http://localhost:8080/emp/auth/login
Content-Type: application/json

{
  "emp_code" : "2024061",
  "emp_pass" : "2024062"

}


### 사원등록
POST http://localhost:8080/employee/empRegist
Content-Type:application/json

{
  "emp_code": "2024061",
  "emp_name": "복구",
  "emp_pass": "2024061",
  "social_security_no": "111111-1111111",
  "hire_date": "2024-06-12",
  "emp_status": "Y"
}

### 회원 주소록 전체 조회
GET http://localhost:8080/address/select

### 받은 쪽지 전체 조회
GET http://localhost:8080/emp/message/receive
Authorization: Bearer eyJkYXRlIjoxNzE5Mjg3NzUyMTY3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTkyOTEzNTJ9.C8bbPSGiKlk0Wanx9hEL0k0HLLiLzGvTxhKoJHvasE_IFcmsRTanLmDDvdTFtQKSOUrhxGZVg04G5bgmd8FYmQ

### 보낸 쪽지 전체 조회
GET http://localhost:8080/emp/message/send
Authorization: Bearer eyJkYXRlIjoxNzE5Mjg3NzUyMTY3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTkyOTEzNTJ9.C8bbPSGiKlk0Wanx9hEL0k0HLLiLzGvTxhKoJHvasE_IFcmsRTanLmDDvdTFtQKSOUrhxGZVg04G5bgmd8FYmQ

### 받은 쪽지 휴지통 PUT
PUT http://localhost:8080/emp/message/receive/MS71/bin
Content-Type: application/json

{
  "storCode": 3
}

### 휴지통 전체 조회
GET http://localhost:8080/emp/message/bin
Authorization: Bearer eyJkYXRlIjoxNzE5MzA5MDc0NTAwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTkzMTI2NzR9.Tw1PMbKnQF0ItKncW4DmbdVevIHupJ9kgcfpxiPEP3y7wELnQmzj98e0Txy7_2buJvhJBVjCIdEG3xu-MoXBzA

### 중요 보관함 전체 조회
GET http://localhost:8080/emp/message/important
Authorization: Bearer eyJkYXRlIjoxNzE5MzA5MDc0NTAwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTkzMTI2NzR9.Tw1PMbKnQF0ItKncW4DmbdVevIHupJ9kgcfpxiPEP3y7wELnQmzj98e0Txy7_2buJvhJBVjCIdEG3xu-MoXBzA

### 업무 보관함 전체 조회
GET http://localhost:8080/emp/message/work
Authorization: Bearer eyJkYXRlIjoxNzE5MzA5MDc0NTAwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTkzMTI2NzR9.Tw1PMbKnQF0ItKncW4DmbdVevIHupJ9kgcfpxiPEP3y7wELnQmzj98e0Txy7_2buJvhJBVjCIdEG3xu-MoXBzA