### 로그인 테스트
POST http://localhost:8080/emp/auth/login
Content-Type: application/json

{
  "emp_code" : "2024061",
  "emp_pass" : "2024062"

}


### 사원등록
POST http://localhost:8080/employee/empRegist
Content-Type:application/json

{
  "emp_code": "2024061",
  "emp_name": "복구",
  "emp_pass": "2024061",
  "social_security_no": "111111-1111111",
  "hire_date": "2024-06-12",
  "emp_status": "Y"
}

### 회원 주소록 전체 조회
GET http://localhost:8080/address/select

### 받은 쪽지 전체 조회
GET http://localhost:8080/emp/message/receive
Authorization: Bearer eyJkYXRlIjoxNzE4OTU3MTE2MjcwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTg5NjA3MTZ9.Ul-dgMYYE1GGMokybzyskCuEXAhJyXEJ9-akDaoWl2zFF9yYXM5h364rgXv0tVfwm7tseX0IOH94yQ8ZgrlB9Q

### 보낸 쪽지 전체 조회
GET http://localhost:8080/emp/message/send
Authorization: Bearer eyJkYXRlIjoxNzE4OTU3MTE2MjcwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcF9jb2RlIjoyMDI0MDYxLCJleHAiOjE3MTg5NjA3MTZ9.Ul-dgMYYE1GGMokybzyskCuEXAhJyXEJ9-akDaoWl2zFF9yYXM5h364rgXv0tVfwm7tseX0IOH94yQ8ZgrlB9Q
